name: valid
description: This library exposes various Dart primitives as valid, immutable types that can help you write safer Dart code.
version: 0.2.0-nullsafety.0
homepage: https://github.com/oliverfunk/valid

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  built_collection: ^5.0.0-nullsafety
  collection: ^1.15.0-nullsafety
  equatable: ^2.0.0-nullsafety
  logging: ^1.0.0-nullsafety
  meta: ^1.3.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test:
