name: valid
description: This library exposes various Dart primitives as valid, immutable types that can help you write safer Dart code.
version: 0.1.0
homepage: https://github.com/oliverfunk/valid

environment:
  sdk: ">=2.10.0 <3.0.0"
